#!/bin/bash

# INSTALL for AcetoScan

#- Last modified: fre jul 19, 2019 20:51
#- Sign: Abhi

# setting pipefail

set -euo pipefail

##      Installation

##      Checking and installing Dependencies

echo -e "\n#Checking and installing dependencies for debian/ubuntu based systems"

###     Checking if cutadapt is installed


if ! command -v "cutadapt" > /dev/null ; then
        echo -e "\n#Installing Cutadapt"    
        sudo apt install -y -qq cutadapt=1.18-1 
fi

###     Checking if vsearch is installed

if ! command -v "vsearch" > /dev/null ; then
        echo -e "\n#Installing Vsearch"
        wget "https://github.com/torognes/vsearch/releases/download/v2.13.1/vsearch-2.13.1-linux-x86_64.tar.gz"
        tar xzf vsearch-2.13.1-linux-x86_64.tar.gz
        sudo cp vsearch-2.13.1-linux-x86_64/bin/vsearch /usr/local/bin/vsearch
fi

###     Checking if Blast is installed

if ! command -v "blastx" > /dev/null ; then
        echo -e "\n#Installing NCBI-blast+"
        sudo apt install -y -qq ncbi-blast+ 
fi

###     Checking if bioperl is installed

        echo -e "\n#Checking BioPerl"
        sudo apt install -y -qq bioperl 


###     Checking if R and Rscript are installed

if ! command -v "R" > /dev/null ; then
        echo -e "\n#Installing R"
        sudo apt install -y -qq libnode-dev 
        sudo apt install -y -qq r-base 
        sudo apt install -y -qq r-base-dev 
fi

###     Installing R packages 

echo -e "\n#Checking/Fixing R dependencies"
        sudo apt install -y -qq r-bioc-phyloseq 
        sudo apt install -y -qq r-cran-dplyr 
        sudo apt install -y -qq r-cran-ggplot2 
        sudo apt install -y -qq r-cran-plotly 
        sudo apt install -y -qq r-cran-plyr 
        sudo apt install -y -qq r-cran-rcolorbrewer 

###     Copying Acetoscan executable to /usr/local/bin

sudo find / -type f -name "acetoscan" -exec cp {} /usr/local/bin/ \; 2>/dev/null
sudo chmod +x /usr/local/bin/acetoscan

###     fixing the directory for AcetoScan program

user=`echo ${SUDO_USER:-${USER}}`

mkdir -m 777 -p /home/$user/acetoscan/acetoscan_bin
mkdir -m 777 -p /home/$user/acetoscan/acetobase
mkdir -m 777 -p /home/$user/acetoscan/output_data

###     copying acetoscan dependencies to acetoscan_bin

cp ./acetoscan_bin/* /home/$user/acetoscan/acetoscan_bin/
sudo chmod +x /home/$user/acetoscan/acetoscan_bin/*

###     Downloading AcetoBase

#echo -e "\n#Downloading AcetoBase"
#wget -O /home/$user/acetoscan/acetobase/AcetoBase_V1.tar.gz https://acetobase.molbio.slu.se/download/acetobase_ref_protein
#tar xf /home/$user/acetoscan/acetobase/AcetoBase_V1.tar.gz -C /home/$user/acetoscan/acetobase/ 
#find /home/$user/ -type f -iname "AcetoBaseV1.fasta" -exec cp {} /home/$user/acetoscan/acetobase/AcetoBaseV1.fasta
#cd /home/$user/acetoscan/acetobase/ && makeblastdb -in AcetoBaseV1.fasta -dbtype prot -title AcetoBaseV1 -out AcetoBaseV1

###     End of script 
